// COMANDO DI ESECUZIONE DA MONGOSH SVILUPPO
/*
     mongosh "mongodb://giuldegi:bitbros@192.168.248.135:27017/romagna?authSource=admin" ^
  --quiet ^
  --file "C:\Appo09\Mongo_Prod_EXP\001_mongosh_count_IHUB_records.js"
*/
// COMANDO DI ESECUZIONE DA MONGOSH ESERCIZIO/TEST
/*
     mongosh "mongodb://root:password@localhost:47017/hc40-index?authSource=admin&directConnection=true&readPreference=primaryPreferred" ^
  --quiet ^
  --file "C:\Appo09\Mongo_Prod_EXP\001_mongosh_count_IHUB_records.js"
*/

// COMANDO DI ESECUZIONE DA MONGOSH TEST UBUNTU
/*

/data/mongosh/bin/mongosh "mongodb://root:password@mongo-rs-1.mongo-rs-svc.mongodb.svc.cluster.local:27017/hc40-index-bck?authSource=admin&directConnection=true&readPreference=primary" \
  --quiet \
  --file "/data/Mongo_Sh_Script/001_mongosh_count_IHUB_records.js"

 spostare il file da windows a ubuntu kubernate:
 Get-Content -Raw "C:\Users\giuldegi\OneDrive - Engineering Ingegneria Informatica S.p.A\Desktop\ENG\SANITA\Romagna\CDR-Mongo\Svil\BONIFICA_CDR\001_mongosh_count_IHUB_records.js" |
kubectl -n ellipse-index exec -i ubuntu-mongosync-6845564564-zvnn9 -- sh -c 'cat > /data/Mongo_Sh_Script/001_mongosh_count_IHUB_records.js'

 OUTPUT:
countDocuments Encounter/IHUB.: 45125

*/

const { readRuntimeAndContext } = require("/data/Mongo_Sh_Script/lib/read_context.js");

(async () => {
  // Phase-evolved: context generated by orchestrator
  const { runtime, context } = readRuntimeAndContext();

  const runId = runtime?.runId || context?.runId || null;
  const stepId = context?.step?.id ?? null;
  const dbName = runtime?.mongo?.dbName || context?.mongo?.dbName || null;

  // Params may come from pipeline "params"
  const params = context?.params || {};
  const coll = params.collection || "encounter";
  const idPrefixStart = params.idPrefixStart || "Encounter/IHUB.";
  const idPrefixEnd = params.idPrefixEnd || "Encounter/IHUB/";

  const filter = { _id: { $gte: idPrefixStart, $lt: idPrefixEnd } };

  // Use connection-level db selection (mongosh URI contains /<dbName>)
  // 'db' here refers to the database selected by the connection string.
  const n = await db.getCollection(coll).countDocuments(filter);

  // Human-readable output (kept)
  print(`countDocuments ${idPrefixStart}: ${n}`);

  // Machine-friendly output (single-line JSON)
  print(
    JSON.stringify({
      type: "result",
      script: "001_mongosh_count_IHUB_records.js",
      runId,
      stepId,
      dbName,
      collection: coll,
      filter,
      count: n,
      ts: new Date().toISOString(),
    })
  );
})().catch((err) => {
  print("ERROR: " + (err && err.stack ? err.stack : err));
  quit(1);
});

// conteggio in produzione al 18/03/2026: 115683
// conteggio in test countDocuments Encounter/IHUB.: 45121